In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('income_per_section/dataSet_3.csv')
data

,Unnamed: 0,Unnamed: 0.1,Instituto,Localidad,Presentados,Aptos,Media Expediente,Media PAU,coordinate,NumBib 2 km,NumBib 5 km,NumBib 8 km,NumBib 10 km,lat,long,income
0,0,0,CENTRE PRIVAT LA PURÍSIMA,ALZIRA,34,34,7.9,6.6,"[39.153307, -0.4422964]",0,3,7,7,39.153307,-0.442296,10512.0
1,1,1,IES REI EN JAUME,ALZIRA,59,56,7.6,6.2,"[39.146734, -0.4306395]",0,1,5,7,39.146734,-0.430640,9116.0
2,2,2,IES JOSÉ MARÍA PARRA,ALZIRA,39,36,7.0,5.2,"[39.1569694, -0.4292533]",0,1,5,7,39.156969,-0.429253,6739.0
3,3,3,CENTRE PRIVAT NUESTRA SEÑORA DE LA SALUD,ALGEMESÍ,30,30,8.2,7.1,"[39.1827727, -0.4375332]",1,3,6,9,39.182773,-0.437533,4631.0
4,4,4,IES SANT VICENT FERRER,ALGEMESÍ,30,30,8.0,7.1,"[39.1858352, -0.4375209]",1,3,6,9,39.185835,-0.437521,9683.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,456,457,ES L'ALLUSSER,MUTXAMEL,28,24,7.3,5.0,"[38.4209557, -0.4456107]",1,8,15,44,38.420956,-0.445611,NaN
457,457,458,CENTRO PRIVADO SAN ALBERTO MAGNO,MONFORTE DEL CID,8,8,8.4,5.8,"[38.38134, -0.7189599999999999]",1,1,3,3,38.381340,-0.718960,NaN
458,458,459,IES MARÍA BLASCO,SANT VICENT DEL RASPEIG,50,49,7.5,5.5,"[38.3905117, -0.5212411]",3,11,42,44,38.390512,-0.521241,NaN
459,459,460,CENTRE PRIVAT EL VALLE,ALACANT,10,10,7.9,6.9,"[38.5793, -0.1033]",1,5,9,10,38.579300,-0.103300,NaN
460,460,461,CENTRE PRIVAT ÁNGEL DE LA GUARDA III,ALACANT,38,38,7.8,6.2,"[38.3666306, -0.4544057]",1,35,40,46,38.366631,-0.454406,NaN

In [3]:
# I take only the data with an income data
data = data.dropna()
data

,Unnamed: 0,Unnamed: 0.1,Instituto,Localidad,Presentados,Aptos,Media Expediente,Media PAU,coordinate,NumBib 2 km,NumBib 5 km,NumBib 8 km,NumBib 10 km,lat,long,income
0,0,0,CENTRE PRIVAT LA PURÍSIMA,ALZIRA,34,34,7.9,6.6,"[39.153307, -0.4422964]",0,3,7,7,39.153307,-0.442296,10512.0
1,1,1,IES REI EN JAUME,ALZIRA,59,56,7.6,6.2,"[39.146734, -0.4306395]",0,1,5,7,39.146734,-0.430640,9116.0
2,2,2,IES JOSÉ MARÍA PARRA,ALZIRA,39,36,7.0,5.2,"[39.1569694, -0.4292533]",0,1,5,7,39.156969,-0.429253,6739.0
3,3,3,CENTRE PRIVAT NUESTRA SEÑORA DE LA SALUD,ALGEMESÍ,30,30,8.2,7.1,"[39.1827727, -0.4375332]",1,3,6,9,39.182773,-0.437533,4631.0
4,4,4,IES SANT VICENT FERRER,ALGEMESÍ,30,30,8.0,7.1,"[39.1858352, -0.4375209]",1,3,6,9,39.185835,-0.437521,9683.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,240,241,IES RASCANYA-ANTONIO CAÑUELO,VALÈNCIA,18,18,7.6,6.3,"[39.494429, -0.3605372]",29,199,236,257,39.494429,-0.360537,15930.0
241,241,242,CENTRE ESPECÍFIC D'EDUCACIÓ A DISTÀNCIA CEED,VALÈNCIA,20,16,6.2,5.0,"[39.464629, -0.411091]",37,194,261,276,39.464629,-0.411091,6920.0
242,242,243,IES MARÍA CARBONELL I SÁNCHEZ,BENETÚSSER,25,24,7.5,6.4,"[39.419887, -0.4014005]",12,29,223,261,39.419887,-0.401400,8934.0
243,243,244,IES DE SAN ANTONIO DE BENAGÉBER,SAN ANTO. DE BENAGÉBER,35,35,7.7,6.8,"[39.5630656, -0.5022515]",3,14,15,29,39.563066,-0.502252,13209.0
245,245,246,CENTRE PRIVAT CUMBRES SCHOOL,MONCADA,34,33,8.1,7.1,"[39.5494861, -0.4036889]",3,15,62,225,39.549486,-0.403689,12913.0

In [4]:
data[['Media Expediente','Media PAU','income']].corr(method ='pearson')

                  Media Expediente  Media PAU    income
Media Expediente          1.000000   0.558445  0.052204
Media PAU                 0.558445   1.000000  0.192983
income                    0.052204   0.192983  1.000000