In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

data = pd.read_csv('Grades/dataSet.csv')
data

,Unnamed: 0,Instituto,Localidad,Presentados,Aptos,Media Expediente,Media PAU,coordinate,NumBib 2 km,NumBib 5 km,NumBib 8 km,NumBib 10 km
0,0,CENTRE PRIVAT LA PURÍSIMA,ALZIRA,34,34,7.9,6.6,"[39.153307, -0.4422964]",0,3,7,7
1,1,IES REI EN JAUME,ALZIRA,59,56,7.6,6.2,"[39.146734, -0.4306395]",0,1,5,7
2,2,IES JOSÉ MARÍA PARRA,ALZIRA,39,36,7.0,5.2,"[39.1569694, -0.4292533]",0,1,5,7
3,3,CENTRE PRIVAT NUESTRA SEÑORA DE LA SALUD,ALGEMESÍ,30,30,8.2,7.1,"[39.1827727, -0.4375332]",1,3,6,9
4,4,IES SANT VICENT FERRER,ALGEMESÍ,30,30,8.0,7.1,"[39.1858352, -0.4375209]",1,3,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...
456,457,ES L'ALLUSSER,MUTXAMEL,28,24,7.3,5.0,"[38.4209557, -0.4456107]",1,8,15,44
457,458,CENTRO PRIVADO SAN ALBERTO MAGNO,MONFORTE DEL CID,8,8,8.4,5.8,"[38.38134, -0.7189599999999999]",1,1,3,3
458,459,IES MARÍA BLASCO,SANT VICENT DEL RASPEIG,50,49,7.5,5.5,"[38.3905117, -0.5212411]",3,11,42,44
459,460,CENTRE PRIVAT EL VALLE,ALACANT,10,10,7.9,6.9,"[38.5793, -0.1033]",1,5,9,10
460,461,CENTRE PRIVAT ÁNGEL DE LA GUARDA III,ALACANT,38,38,7.8,6.2,"[38.3666306, -0.4544057]",1,35,40,46

In [8]:
data[['Media Expediente','Media PAU','NumBib 2 km','NumBib 5 km','NumBib 8 km','NumBib 10 km']].corr(method ='pearson')

,Media Expediente,Media PAU,NumBib 2 km,NumBib 5 km,NumBib 8 km,NumBib 10 km
Media Expediente,1.000000,0.482846,0.008478,-0.026223,-0.024364,0.009299
Media PAU,0.482846,1.000000,0.072162,0.008418,-0.019883,-0.008756
NumBib 2 km,0.008478,0.072162,1.000000,0.821374,0.677203,0.614263
NumBib 5 km,-0.026223,0.008418,0.821374,1.000000,0.898007,0.829367
NumBib 8 km,-0.024364,-0.019883,0.677203,0.898007,1.000000,0.975340
NumBib 10 km,0.009299,-0.008756,0.614263,0.829367,0.975340,1.000000

We Want to find a correlation between the grades and the number of nearby libraries.
That correspond to a correlation between the variable NumBib n km and Media Expediente and Media PAU

In [9]:
data[['Media Expediente','Media PAU','NumBib 2 km','NumBib 5 km','NumBib 8 km','NumBib 10 km']].corr(method="kendall")

,Media Expediente,Media PAU,NumBib 2 km,NumBib 5 km,NumBib 8 km,NumBib 10 km
Media Expediente,1.000000,0.328687,-0.056775,-0.063386,-0.042935,-0.035303
Media PAU,0.328687,1.000000,-0.039272,-0.054140,-0.047395,-0.047390
NumBib 2 km,-0.056775,-0.039272,1.000000,0.747647,0.612501,0.560271
NumBib 5 km,-0.063386,-0.054140,0.747647,1.000000,0.803977,0.740163
NumBib 8 km,-0.042935,-0.047395,0.612501,0.803977,1.000000,0.900263
NumBib 10 km,-0.035303,-0.047390,0.560271,0.740163,0.900263,1.000000

In [10]:
data[['Media Expediente','Media PAU','NumBib 2 km','NumBib 5 km','NumBib 8 km','NumBib 10 km']].corr(method="spearman")

,Media Expediente,Media PAU,NumBib 2 km,NumBib 5 km,NumBib 8 km,NumBib 10 km
Media Expediente,1.000000,0.438891,-0.077335,-0.088036,-0.059893,-0.049463
Media PAU,0.438891,1.000000,-0.054629,-0.079609,-0.070197,-0.068974
NumBib 2 km,-0.077335,-0.054629,1.000000,0.879120,0.773022,0.729860
NumBib 5 km,-0.088036,-0.079609,0.879120,1.000000,0.929082,0.890858
NumBib 8 km,-0.059893,-0.070197,0.773022,0.929082,1.000000,0.972890
NumBib 10 km,-0.049463,-0.068974,0.729860,0.890858,0.972890,1.000000